# Docker compose file for an example redis stack server
services:
    redis-stack-server:
        container_name: redis-stack-server
        volumes:
            - /tmp/docker/redis-stack-server/data/redis:/data/redis
            - ./redis-stack.conf:/etc/configuration/redis-stack.conf
            - ./users.acl:/etc/users.acl
        environment:
            - REDIS_USERNAME=ping
            - REDIS_PASSWORD=pong
        ports:
            - "6379:6379"
        restart: always
        image: redis/redis-stack-server:latest
        command: [ "redis-server", "etc/configuration/redis-stack.conf" ]
        healthcheck:
            test: "sh -c 'redis-cli --user $$REDIS_USERNAME --pass $$REDIS_PASSWORD --no-auth-warning ping'"
            timeout: 30s
            retries: 5
            start_period: 10s
    redis-cli:
        container_name: redis-cli
        environment:
            - REDIS_HOST=redis-stack-server
            - REDIS_PORT=6379
            - REDIS_USERNAME=import
            - REDIS_PASSWORD=triggersNfunctions
        depends_on:
            redis-stack-server:
                condition: service_healthy
        image: redis:latest
        volumes:
            - ./triggers-functions:/app/triggers-functions
            - ./tfunctions_load.sh:/app/tfunctions_load.sh
        entrypoint: [ "/app/tfunctions_load.sh" ]